Repository taysmith99/PT-GUI, pull requests merged in 2022-03, with the labels that each got.

#1 Updated Readme
  README.md
Labels: documentation

#3 feat: add ci via github actions
  .github/workflows/pylint.yml
  .pylintrc
  about_page.py
  common_utils.py
  main.py
  nav_bar.py
  references_page.py
  requirements.txt
  start_page.py
  tool_descriptions.py
  tools_page.py
  vector_descriptions.py
  vectors_page.py
  walkthrough_descriptions.py
  walkthroughs_page.py
Labels: enhancement

#5 feat: add shinx docs generated by github-actions
  .github/workflows/docs_ci.yml
  .github/workflows/docs_update.yml
  .github/workflows/pylint.yml
  .gitignore
  docs/Makefile
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation, enhancement
